### ISSUE TITLE
Recent versions of SonarQube now only have overall coverage

### ISSUE THREAD

**Issue by michelzanini** [Inform-Software/sonar-groovy#10]
On recent version of SonarQube, UnitTest and IntegrationTest coverage have being unified into just one overall coverage.

With that, properties such as sonar.jacoco.reportPath has being deprecated and now sonar.jacoco.reportPaths is introduced. No longer we have things like sonar.jacoco.itReportPath, etc...

Maybe we should update the Groovy plugin to go in the same direction.
That means deprecating/removing support for sonar.groovy,jacoco.reportPath and sonar.groovy,jacoco.itReportPath and adding sonar.groovy,jacoco.reportPaths?

**Comment by TobiX** [comment]
I'm probably not updating the properties, since (as you mentioned in #11) analysing the binary JaCoCo files is now deprecated and using the XML files supports Groovy without any change to the Groovy plugin (yay!). I already merged the classes and only report the overall coverage to the SonarQube server...

**Comment by TobiX** [comment]
Version 1.6 only reports merged coverage. As mentioned, I won't touch the property names.

**Comment by philbert** [comment]
Great! Was just looking into how this would be handled in the future. Now it's clear we need to move to ```sonar.coverage.jacoco.xmlReportPaths``` from the legacy way of splitting coverage for IT and UT.
